In [2]:
#Data Manipulation
import pandas as pd
import numpy as np

import matplotlib as plt

In [3]:
#Reading CSV
df=pd.read_csv('train.csv')

In [10]:
print(df.shape)
df.head()

(47803, 37)

,animal_id_outcome,dob_year,dob_month,age_upon_intake,animal_type,breed,color,intake_condition,intake_type,sex_upon_intake,...,age_upon_outcome_(years),age_upon_outcome_age_group,outcome_datetime,outcome_month,outcome_year,outcome_monthyear,outcome_weekday,outcome_hour,outcome_number,outcome_type
0,A006100,2007,7,10 years,Dog,Spinone Italiano Mix,Yellow/White,Normal,Stray,Neutered Male,...,10.0,"(7.5, 10.0]",2017-12-07 14:07:00,12,2017,2017-12,Thursday,0,1.0,Return to Owner
1,A006100,2007,7,7 years,Dog,Spinone Italiano Mix,Yellow/White,Normal,Public Assist,Neutered Male,...,7.0,"(5.0, 7.5]",2014-12-20 16:35:00,12,2014,2014-12,Saturday,16,2.0,Return to Owner
2,A006100,2007,7,6 years,Dog,Spinone Italiano Mix,Yellow/White,Normal,Public Assist,Neutered Male,...,6.0,"(5.0, 7.5]",NaN,3,2014,2014-03,Saturday,17,3.0,Return to Owner
3,A047759,2004,4,10 years,Dog,Dachshund,Tricolor,Normal,Owner Surrender,Neutered Male,...,10.0,"(7.5, 10.0]",2014-04-07 15:12:00,4,2014,2014-04,Monday,15,1.0,Missing
4,A134067,1997,10,16 years,Dog,Shetland Sheepdog,Brown/White,Injured,Public Assist,Neutered Male,...,16.0,"(15.0, 17.5]",2013-11-16 11:54:00,11,2013,2013-11,Saturday,11,1.0,Return to Owner

In [34]:
print(df.dtypes)

animal_id_outcome              object
dob_year                        int64
dob_month                       int64
age_upon_intake                object
animal_type                    object
breed                          object
color                          object
intake_condition               object
intake_type                    object
sex_upon_intake                object
count                           int64
age_upon_intake_(days)          int64
age_upon_intake_(years)       float64
age_upon_intake_age_group      object
intake_datetime                object
intake_month                    int64
intake_year                     int64
intake_monthyear               object
intake_weekday                 object
intake_hour                     int64
intake_number                 float64
time_in_shelter                object
time_in_shelter_days          float64
age_upon_outcome               object
date_of_birth                  object
sex_upon_outcome               object
age_upon_outcome_(days)         int64
age_upon_outcome_(years)      float64
age_upon_outcome_age_group     object
outcome_datetime               object
outcome_month                   int64
outcome_year                    int64
outcome_monthyear              object
outcome_weekday                object
outcome_hour                    int64
outcome_number                float64
outcome_type                   object
dtype: object

In [6]:
df['animal_type'].unique()

array(['Dog', 'Cat', 'Other', 'Bird'], dtype=object)

In [31]:
df['animal_id_outcome'].unique().tolist()
pd.isnull('animal_id_outcome')

False